from enum import Enum

ValidationCode = Enum(
    'ValidationCode',
    """
    unclassified
    preParse_nullBytes
    preParse_encoding
    preParse_byteOrderMark
    preParse_byteOrderMark_corrupt
    xml_encoding_decl
    xml_entity_decl
    xml_document_validity
    xml_parse
    xml_xsd
    xml_id_unique
    xml_id_unqualified
    xml_root_element
    xml_tt_namespace
    ebuttd_document_validity
    ebuttd_p_xml_id_constraint
    ebuttd_empty_body_constraint
    ebuttd_empty_div_constraint
    ebuttd_head_element_constraint
    ebuttd_layout_element_constraint
    ebuttd_multiRowAlign
    ebuttd_nested_div_constraint
    ebuttd_nested_span_constraint
    ebuttd_nested_timing_constraint
    ebuttd_overlapping_region_constraint
    ebuttd_region_element_constraint
    ebuttd_region_attributes_constraint
    ebuttd_region_position_constraint
    ebuttd_style_element_constraint
    ebuttd_inline_styling_constraint
    ebuttd_styling_element_constraint
    ebuttd_timing_attribute_constraint
    imsc_parameter_activeArea
    ttml_attribute_styling_attribute
    ttml_parameter_cellResolution
    ebuttd_parameter_timeBase
    ttml_document_timing
    ttml_document_validity
    ttml_element_body
    ttml_element_br
    ttml_element_head
    ttml_element_layout
    ttml_element_region
    ttml_element_style
    ttml_element_styling
    ttml_metadata_copyright
    ttml_layout_region_association
    ttml_styling
    ttml_styling_reference
    ttml_styling_referential_chained
    ttml_styling_attribute_applicability
    bbc_document_validity
    bbc_block_backgroundColor_constraint
    bbc_region_attributes_constraint
    bbc_region_backgroundColor_constraint
    bbc_region_overflow_constraint
    bbc_region_position_constraint
    bbc_text_backgroundColor_constraint
    bbc_text_color_constraint
    bbc_text_fillLineGap_constraint
    bbc_text_fontFamily_constraint
    bbc_text_fontSize_constraint
    bbc_text_fontStyle_constraint
    bbc_text_lineHeight_constraint
    bbc_text_linePadding_constraint
    bbc_text_multiRowAlign_constraint
    bbc_text_span_constraint
    bbc_timing_gaps
    bbc_timing_minimum_subtitles
    bbc_timing_segment_overlap
    validator_internal_exception
    """
    )
